[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
evm_version = "paris"
optimizer = true
optimizer_rounds = 200
fs_permissions = [{ access = "read", path = "./broadcast" }]
gas_reports = ["Flamelings"]

# --chains--
[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
sepolia = "${RPC_SEPOLIA}"
goerli = "${RPC_GOERLI}" 
bsc = "${RPC_BSC}"
bsctest = "${RPC_BSC_TEST}"
base = "${RPC_BASE}"
baseSepolia = "${RPC_BASE_SEPOLIA}"
baseGoerli = "${RPC_BASE_GOERLI}"
avax = "${RPC_AVAX}"
avaxTest = "${RPC_AVAX_FUJI}"

localhost = "${RPC_LOCALHOST}"

# --scans--
[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}"}
sepolia = { key = "${ETHERSCAN_KEY}", chain = "11155111"}
goerli = { key = "${ETHERSCAN_KEY}", chain = "5" }
bsc = { key = "${BSCSCAN_KEY}", chain = "56" }
bsctest = { key = "${BSCSCAN_KEY}", chain = "97" }
base = { key = "${BASESCAN_KEY}", chain = "8453"}
baseSepolia = { key = "${BASESCAN_SEPOLIA_KEY}", chain = "84532", url = "https://base-sepolia.blockscout.com/api" }
baseGoerli = { key = "${BASESCAN_KEY}", chain = "84531" }
avax = {key="${SNOWTRACE_KEY}", chain="43114", url='https://api.routescan.io/v2/network/mainnet/evm/43114/etherscan'}
avaxTest = {key="${SNOWTRACE_KEY}", chain="43113", url='https://api.routescan.io/v2/network/testnet/evm/43113/etherscan'}